# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d8681bbbfdd2d425c14b6f2a45fd2ddeed0856e19694ad9a46a077efc0ce403c7d28216fe0d125574104247c39965fb79510b8d675b088ebd89fbb38c7f8a9

test:
  secret_key_base: 3bf696697bff8b173c9a92ed31d4e99ed6d51a58e5d1cfe437ef806fd4a2be021240497fd8dc5d27b4d6710464f57e7461053b406bff5cc5117d16b2973dd647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
